language: ruby
os: linux
dist: xenial
jdk: openjdk8
rvm:
- 3.1.2

before_deploy:
  - gem update --system
  - gem install ffi -v 1.17.1
  - gem install jekyll -v 4.1.0 && gem install jekyll-redirect-from && gem install s3_website

script: jekyll build

after_success:
- test $TRAVIS_BRANCH = "staging" && s3_website push --config-dir=_config/staging/
- test $TRAVIS_BRANCH = "main" && s3_website push --config-dir=_config/production/

branches:
  only:
  - staging
  - main

jobs:
  include:
    - stage: deploy
      if: branch = staging OR branch = main
      script: skip
      before_deploy:
        - gem update --system
        - gem install jekyll -v 4.1.0 && gem install jekyll-redirect-from && gem install s3_website
      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: srccon-2025
          region: us-east-1
          skip_cleanup: true
          local_dir: _site
          on:
            branch: staging
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: srccon-2025-staging
          region: us-east-1
          skip_cleanup: true
          local_dir: _site
          on:
            branch: main

notifications:
  slack:
    rooms:
      secure:
