language: ruby
os: linux
dist: xenial
jdk: openjdk8
rvm:
- 3.1.2

before_deploy:
  - rvm use 3.1.2

install: gem install jekyll -v 4.1.0 && gem install jekyll-redirect-from && gem install
  s3_website_revived

script: jekyll build

after_success:
  - test $TRAVIS_BRANCH = "staging" && s3_website push --config-dir=_config/staging/ --site_dir=_site
  - test $TRAVIS_BRANCH = "main" && s3_website push --config-dir=_config/production/ --site_dir=_site

branches:
  only:
  - staging
  - main

notifications:
  slack:
    rooms:
      secure:
