name: SRCCON 2025
url: https://2025.srccon.org
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
gems:
  - jekyll-redirect-from
exclude: ['*.yml']
collections:
  transcripts:
    output: true
    permalink: /:collection/:title/
  share:
    output: true
    permalink: /:collection/:slug/

defaults:
  - scope:
      path: ""
    values:
      # event_name: set this value to something like SRCCON 2020 or SRCCON:LEAD
      event_name: SRCCON 2025
      # event_date: set this value to something like July 11 & 12
      event_date: July 10 -11
      # event_place: set this value to something like Minneapolis
      event_place: Minneapolis, MN
      # event_place_abbreviation: set this value to something like MPLS
      event_place_abbreviation: MPLS
      # description: this value is used for meta tags AND the top of the homepage
      # html will be stripped for meta tags. Rewrite this for a topical SRCCON!
      description: A peer-led conference from <a href="https://opennews.org">OpenNews</a> for&nbsp;journalists who want to transform their work, their organizations, and their communities.
      # layout: set this value to layout_with_header_image for pages with images at top
      layout: simple_layout
      # cta_button_text: give this a value to enable the orange "call to action" button
      cta_button_text: Propose a session!
      # cta_button_link: set this value to a URL for the orange button (ticket form, etc)
      cta_button_link: https://2025.srccon.org/participation/form/
  - scope:
      path: ""
      type: "transcripts"
    values:
      layout: simple_layout
      section: remote
  - scope:
      path: ""
      type: "share"
    values:
      layout: simple_layout
      section: share
